apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    logging {
      level = "info"
      format = "logfmt"
    }

    local.file_match "container_logs" {
      path_targets = [{"__path__" = "/var/log/containers/*.log"}]
    }

    loki.source.file "container_logs" {
      targets    = local.file_match.container_logs.targets
      forward_to = [loki.write.loki_receiver]
    }

    loki.write "loki_receiver" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }