provider:
  name: aws
env:
  - name: AWS_DEFAULT_REGION
    value: us-east-1

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/ky-tf-ExternalDNSRole # Replace with your IAM role ARN
