apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
spec:
  selector:
    app: opentelemetrycollector
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
    - name: metrics
      port: 8889
      targetPort: 8889
  type: ClusterIP